### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by mikegerber** [hnesk/browse-ocrd#17]
When I open a PAGE view on the attached workspace and click on the first `TextRegion` browse-ocrd segfaults.

* [Screen recording](https://drive.google.com/file/d/1vI56HDA4xDCz2cFr98ibOrnHIDV6A-2t/view?usp=sharing)
* [Workspace](https://github.com/hnesk/browse-ocrd/files/5423451/actevedef_718448162.first-page%2Bbinarization%2Bsegmentation.zip)

I'm not sure if I'm using the program correctly, so I have no idea what it should do instead ;-)

**Comment by hnesk** [comment]
Everything's correct from your side.
Looks like the problem was a Gtk.Scrollable (Gtk.SourceView) inside a Gtk.Scrollable (Gtk.Viewport). The segfault was triggered by all bigger XML-Files.
