### ISSUE TITLE
cannot run in Python pre 3.7.2 anymore

### ISSUE THREAD

**Issue by bertsky** [hnesk/browse-ocrd#22]
With the recent additions, I get:
```
   File "/lib/python3.6/site-packages/ocrd_browser/util/config.py", line 5, in <module>
    from typing import List, Optional, OrderedDict as OrderedDictType
ImportError: cannot import name 'OrderedDict'
```

(This is Python 3.6.7 – `typing.OrderedDict` was only [introduced](https://docs.python.org/3/library/typing.html#typing.OrderedDict) in 3.7.2.)

How can we avoid this dependency?

**Comment by hnesk** [comment]
As this was only some experimental code for an idea of "autoconfiguration", I removed it for now

**Comment by bertsky** [comment]
Thanks!
