### ISSUE TITLE
PageView: component menu not editable

### ISSUE THREAD

**Issue by bertsky** [hnesk/browse-ocrd#35]
For me sometimes the Gtk.Menu of the PageFeaturesSelector is grayed out (so I cannot de/activate components).

I have not found a reason or workaround yet myself. (Tried `item.set_sensitive(True)` without effect...)

**Comment by hnesk** [comment]
Hmmm, can't reproduce... 
Is the whole menu label "Show: 🖺🗋🗌↯⬓𝌆–𝌶𝍖‽" grayed out or are single features grayed out? 

For single features, the sensitivity gets set in [`PageFeaturesSelector.set_page()`](https://github.com/hnesk/browse-ocrd/blob/master/ocrd_browser/view/page.py#L214-L218), is this were you tried `item.set_sensitive(True)`?

Does it happen in specific PAGE-XMLs or generally?

**Comment by bertsky** [comment]
I can still click the button, but its contents and the menu items are grayed out.

No, I only tried set_sensitive in the constructor. Yes, when I do it in `set_page`, it works.

It only seems to affect PAGE-XML files with a namespace older than 2019-07-15. (Sorry, I did not recognize this earlier.) Other than these menu choices, the old PAGE files work perfectly.
