### ISSUE TITLE
use last fileGrp as default

### ISSUE THREAD

**Issue by bertsky** [hnesk/browse-ocrd#60]
https://github.com/hnesk/browse-ocrd/blob/14cee74566ce1d94995d69eaa0baf658ec7d31fa/ocrd_browser/view/base.py#L84-L85

This often does not exist in real life (DFG profile has `DEFAULT` or `MAX` or `ORIGINAL`), and has empty PAGE XML anyway. So IMO it would make more sense to pick the **last fileGrp with PAGE-XML mimetype** by default.

(Or even better, make this configurable as well, like the default image fileGrp.)

**Comment by hnesk** [comment]
The method use_file_goup() is just the fallback, if not overridden in subclasses. For nearly all subclasses there is a property file_group that will be used instead. I changed the configurator to always select the last entry now. 
Keeping the ticket open for making file_group selection also configurable.

**Comment by bertsky** [comment]
> For nearly all subclasses there is a property file_group that will be used instead.

Oh right! Sry, forgot all about that. 



> I changed the configurator to always select the last entry now.

Thank you!

**Comment by bertsky** [comment]
> > I changed the configurator to always select the last entry now.
> 
> Thank you!

Which did of course solve the issue.
