### ISSUE TITLE
Application crashes on launch

### ISSUE THREAD

**Issue by SvenMarcus** [hnesk/browse-ocrd#62]
I installed the latest version of `browse-ocrd` from the master branch of the git repository. When launching, I get the following error message:

```python
Traceback (most recent call last):
  File "/usr/local/bin/browse-ocrd", line 5, in <module>
    from ocrd_browser.main import main
  File "/usr/local/lib/python3.10/site-packages/ocrd_browser/main.py", line 26, in <module>
    resources = Gio.resource_load(str(BASE_PATH / "ui.gresource"))
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/usr/local/lib/python3.10/site-packages/ocrd_browser/ui.gresource”: open() failed: No such file or directory (4)
```

It seems that `ui.gresource` is missing. I also cannot find it in the repository, maybe it wasn't pushed with the last update?

**Comment by hnesk** [comment]
Hmm, that file should get generated by `make install` and is excluded from git by purpose. Did you try to install via `make install`?

**Comment by SvenMarcus** [comment]
Oh yeah sorry, that was a mistake on my end. I simply installed it with `pip install git+https://github.com/hnesk/browse-ocrd`
It works fine with `make install`.

**Comment by hnesk** [comment]
Oh, I didn't know that was possible with pip. I just added the generated ui.gresource file to the repository. 27kb is a fair price to pay for that feature.
